name: .NET Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Source/NetClient 
    - name: Build
      run: dotnet build ./Source/NetClient --no-restore
    - name: Test
      run: dotnet test ./Source/NetClient --filter "Type!=Stress" --no-build --verbosity normal
